# –ë–∏–±–ª–∏–æ—Ç–µ–∫–∞ + —Ç–µ—Å—Ç—ã

name: DvStdLib

on:
  push:
    paths:
    - 'engine/libs/dv_std_lib/**'
    - '!engine/libs/dv_std_lib/docs/**'
  pull_request:
    paths:
    - 'dviglo/libs/dv_std_lib/**'
    - '!dviglo/libs/dv_std_lib/docs/**'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
        - {
            id: gcc,
            c: gcc-13,
            cxx: g++-13,
          }
        - {
            id: clang,
            c: clang-18,
            cxx: clang++-18,
          }
        build_type: [debug, release]

    name: üêß-${{ matrix.compiler.id }}-${{ matrix.build_type }}

    steps:
    - name: –£—Å—Ç–∞–Ω–∞–≤–ª–∏–≤–∞–µ–º –Ω–æ–≤–µ–π—à–∏–π CMake
      uses: ssrobins/install-cmake@v1

    - name: –°–∫–∞—á–∏–≤–∞–µ–º —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: repo

    - name: –ì–µ–Ω–µ—Ä–∏—Ä—É–µ–º –ø—Ä–æ–µ–∫—Ç—ã
      run: |
        cmake repo/engine/libs/dv_std_lib -B build -G "Unix Makefiles" \
          -D CMAKE_C_COMPILER=${{ matrix.compiler.c }} -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -D DV_STD_LIB_TESTER=1 -D DV_STD_LIB_UB_SANITIZER=1

    - name: –ö–æ–º–ø–∏–ª–∏—Ä—É–µ–º
      run: |
        cmake --build build --parallel

    - name: CTest
      run: |
        ctest --verbose --test-dir build --timeout 60

  windows:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        compiler: [vs, mingw]
        build_type: [debug, release]

    name: üî≤-${{ matrix.compiler }}-${{ matrix.build_type }}

    steps:
    - name: –£—Å—Ç–∞–Ω–∞–≤–ª–∏–≤–∞–µ–º –Ω–æ–≤–µ–π—à–∏–π CMake
      uses: ssrobins/install-cmake@v1

    - name: –°–∫–∞—á–∏–≤–∞–µ–º —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: repo

    - name: –ì–µ–Ω–µ—Ä–∏—Ä—É–µ–º –ø—Ä–æ–µ–∫—Ç—ã
      shell: bash
      run: |
        args=(repo/engine/libs/dv_std_lib -B build -D DV_STD_LIB_TESTER=1 -D DV_STD_LIB_UB_SANITIZER=1)

        if [ "${{ matrix.compiler }}" == "vs" ]
        then
          args+=(-G "Visual Studio 17 2022")
        else
          args+=(-G "MinGW Makefiles")
          args+=(-D CMAKE_BUILD_TYPE=${{ matrix.build_type }})
        fi

        cmake "${args[@]}"

    - name: –ö–æ–º–ø–∏–ª–∏—Ä—É–µ–º
      shell: bash
      run: |
        args=(--build build --parallel)

        if [ "${{ matrix.compiler }}" == "vs" ]
        then
          args+=(--config ${{ matrix.build_type }})
        fi

        cmake "${args[@]}"

    - name: CTest
      shell: bash
      run: |
        args=(--verbose --test-dir build --timeout 60)

        if [ "${{ matrix.compiler }}" == "vs" ]
        then
          args+=(-C ${{ matrix.build_type }})
        fi

        ctest "${args[@]}"
